# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-14 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0003_testpaper_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.SmallIntegerField(choices=[(1, '審核通過'), (2, '審核未通過'), (3, '等待審核'), (4, '被回報錯誤'), (5, '被回報錯誤，已處理'), (6, '暫存')], default=6),
        ),
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.SmallIntegerField(choices=[(1, '待處理'), (2, '處理中'), (3, '已解決'), (4, '暫存')], default=0),
        ),
    ]
