# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-14 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0003_auto_20191213_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_content',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
