# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-18 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0005_auto_20200216_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='used_freq',
        ),
    ]
