# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-19 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0006_remove_question_used_freq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='used_to',
        ),
        migrations.AddField(
            model_name='testpaper',
            name='question_list',
            field=models.ManyToManyField(to='alcpt.Question'),
        ),
    ]
