# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-24 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0009_auto_20200223_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
