# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-28 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0010_user_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
