# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0011_auto_20200228_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.TextField(null=True),
        ),
    ]
