# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-13 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0011_user_email_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(default=109),
        ),
    ]
