# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-13 11:27
from __future__ import unicode_literals

from django.db import migrations, models
from alcpt.models import Squadron

test_data = ["學生五中隊", "學生六中隊"]

def add_Squadron_data(apps, schema_editor):
    add_app = apps.get_model('alcpt', 'Squadron')
    for new_data in test_data:
        Squadron.objects.create(name = new_data)

def remove_Squadron_data(apps, schema_editor):
    remove_app = apps.get_model('alcpt', 'Squadron')
    for new_data in test_data:
        squadron_to_delete = Squadron.objects.get(name = new_data)
        squadron_to_delete.delete()
        
class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0012_auto_20200113_1122'),
    ]

    operations = [
        migrations.RunPython(add_Squadron_data, remove_Squadron_data)
    ]
