# Generated by Django 3.0.4 on 2020-03-12 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0012_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='testeeList',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
