# Generated by Django 3.0.4 on 2020-03-12 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0013_exam_testeelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TesteeList',
        ),
    ]
