# Generated by Django 3.0.4 on 2020-03-18 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0014_delete_testeelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='proclamation',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proclamation',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proclamation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcer', to=settings.AUTH_USER_MODEL),
        ),
    ]
