# Generated by Django 3.0.4 on 2020-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0015_auto_20200318_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proclamation',
            name='text',
            field=models.TextField(),
        ),
    ]
