# Generated by Django 3.0.4 on 2020-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0017_auto_20200319_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
